spring:
  # 配置数据库连接池
  datasource:
    url: jdbc:mysql://localhost:3306/basic_project?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 130945c
  ### 配置Redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 130945c